name: Deploy docs
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set cache ID
        id: cache_id
        run: echo "value=$(date --utc '+%V')" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ steps.cache_id.outputs.value }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-glightbox
      - run: mkdocs gh-deploy --force